baseURL = "http://hryniew.cz/"
defaultContentLanguage = "en"
title = "Hryniew.cz"

[[imports]]
path = "github.com/jpanther/congo/v2"

[params]
colorScheme = "slate"

[params.author]
name = "Kamil Hryniewicz"
headline = "CTO @ Sameday.AI"
image = "logo.png"

[[params.author.links]]
email = "mailto:kamil@hryniew.cz"
github = "https://github.com/khryniewicz"
keybase = "https://keybase.io/kamilhryniewicz"
linkedin = "https://www.linkedin.com/in/kamilhryniewicz"
medium = "https://medium.com/@khryniewicz"
twitter = "https://twitter.com/KamilHryniewicz"

[params.footer]
showAppearanceSwitcher = true

[params.homepage]
layout = "profile"
